name: repress
channels:
  - conda-forge
  - nvidia
  - bioconda
  - pytorch
dependencies:
  - python>=3.8
  - tensorflow=2.11.*
  - tensorflow-estimator=2.11.*
  - genomekit=5.1.0
  - keras-preprocessing
  - pandas>=2.0
  - numpy>=1.21,<1.25
  - matplotlib
  - seaborn
  - scikit-learn
